export const ListOfAllCard = [
  {
    id: 1,
    name: 'Angular',
    icon: '../assets/images/cards/angular.png',
    flipped: false,
    matched: false,
  },
  {
    id: 2,
    name: 'Angular',
    icon: '../assets/images/cards/angular.png',
    flipped: false,
    matched: false,
  },
  {
    id: 3,
    name: 'D3',
    icon: '../assets/images/cards/d3.png',
    flipped: false,
    matched: false,
  },
  {
    id: 4,
    name: 'D3',
    icon: '../assets/images/cards/d3.png',
    flipped: false,
    matched: false,
  },
  {
    id: 5,
    name: 'Jenkins',
    icon: '../assets/images/cards/jenkins.png',
    flipped: false,
    matched: false,
  },
  {
    id: 6,
    name: 'Jenkins',
    icon: '../assets/images/cards/jenkins.png',
    flipped: false,
    matched: false,
  },
  {
    id: 7,
    name: 'PostCss',
    icon: '../assets/images/cards/postcss.png',
    flipped: false,
    matched: false,
  },
  {
    id: 8,
    name: 'PostCss',
    icon: '../assets/images/cards/postcss.png',
    flipped: false,
    matched: false,
  },
  {
    id: 9,
    name: 'React',
    icon: '../assets/images/cards/react.png',
    flipped: false,
    matched: false,
  },
  {
    id: 10,
    name: 'React',
    icon: '../assets/images/cards/react.png',
    flipped: false,
    matched: false,
  },
  {
    id: 11,
    name: 'Redux',
    icon: '../assets/images/cards/redux.png',
    flipped: false,
    matched: false,
  },
  {
    id: 12,
    name: 'Redux',
    icon: '../assets/images/cards/redux.png',
    flipped: false,
    matched: false,
  },
  {
    id: 13,
    name: 'SASS',
    icon: '../assets/images/cards/sass.png',
    flipped: false,
    matched: false,
  },
  {
    id: 14,
    name: 'SASS',
    icon: '../assets/images/cards/sass.png',
    flipped: false,
    matched: false,
  },
  {
    id: 15,
    name: 'Splendex',
    icon: '../assets/images/cards/splendex.png',
    flipped: false,
    matched: false,
  },
  {
    id: 16,
    name: 'Splendex',
    icon: '../assets/images/cards/splendex.png',
    flipped: false,
    matched: false,
  },
  {
    id: 17,
    name: 'TS',
    icon: '../assets/images/cards/ts.png',
    flipped: false,
    matched: false,
  },
  {
    id: 18,
    name: 'TS',
    icon: '../assets/images/cards/ts.png',
    flipped: false,
    matched: false,
  },
  {
    id: 19,
    name: 'Webpack',
    icon: '../assets/images/cards/webpack.png',
    flipped: false,
    matched: false,
  },
  {
    id: 20,
    name: 'Webpack',
    icon: '../assets/images/cards/webpack.png',
    flipped: false,
    matched: false,
  },
];
